#pragma once

// 网页头部HTML
static const char *ROOT_HTML_1 =
    "<!DOCTYPE html>"
    "<html>"
    "<head>"
    "<meta charset=\"UTF-8\">"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
    "<title>WiFi配置</title>"
    "<style>"
    "body {"
    "    font-family: 'Microsoft YaHei', sans-serif;"
    "    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
    "    margin: 0;"
    "    padding: 0;"
    "    display: flex;"
    "    justify-content: center;"
    "    align-items: center;"
    "    min-height: 100vh;"
    "}"
    ".login-card {"
    "    background: rgba(255, 255, 255, 0.95);"
    "    padding: 40px;"
    "    border-radius: 20px;"
    "    box-shadow: 0 15px 35px rgba(0, 0, 0, 0.2);"
    "    width: 90%;"
    "    max-width: 400px;"
    "    backdrop-filter: blur(10px);"
    "}"
    ".login-card h1 {"
    "    text-align: center;"
    "    color: #333;"
    "    margin-bottom: 30px;"
    "    font-weight: 300;"
    "}"
    ".login-card h1 span {"
    "    color: #764ba2;"
    "    font-weight: 600;"
    "}"
    ".form-group {"
    "    margin-bottom: 20px;"
    "}"
    ".form-group label {"
    "    display: block;"
    "    margin-bottom: 8px;"
    "    color: #555;"
    "    font-weight: 500;"
    "}"
    ".form-control {"
    "    width: 100%;"
    "    padding: 12px 15px;"
    "    border: 2px solid #e1e1e1;"
    "    border-radius: 10px;"
    "    font-size: 16px;"
    "    transition: all 0.3s;"
    "    box-sizing: border-box;"
    "}"
    ".form-control:focus {"
    "    border-color: #764ba2;"
    "    outline: none;"
    "    box-shadow: 0 0 0 3px rgba(118, 75, 162, 0.1);"
    "}"
    ".btn {"
    "    width: 100%;"
    "    padding: 14px;"
    "    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
    "    color: white;"
    "    border: none;"
    "    border-radius: 10px;"
    "    font-size: 16px;"
    "    font-weight: 600;"
    "    cursor: pointer;"
    "    transition: all 0.3s;"
    "}"
    ".btn:hover {"
    "    transform: translateY(-2px);"
    "    box-shadow: 0 7px 14px rgba(0, 0, 0, 0.1);"
    "}"
    ".btn:disabled {"
    "    opacity: 0.6;"
    "    cursor: not-allowed;"
    "    transform: none;"
    "}"
    ".scan-list {"
    "    margin-top: 5px;"
    "    font-size: 14px;"
    "    color: #666;"
    "}"
    ".status {"
    "    text-align: center;"
    "    margin-top: 20px;"
    "    padding: 10px;"
    "    border-radius: 8px;"
    "    font-size: 14px;"
    "}"
    ".status.success {"
    "    background-color: #d4edda;"
    "    color: #155724;"
    "}"
    ".status.error {"
    "    background-color: #f8d7da;"
    "    color: #721c24;"
    "}"
    "</style>"
    "</head>"
    "<body>"
    "<div class=\"login-card\">"
    "    <h1><span>登录</span><br>WiFi配置</h1>"
    "    <form method=\"POST\" action=\"/config\" enctype=\"application/x-www-form-urlencoded\">"
    "        <div class=\"form-group\">"
    "            <label for=\"ssid\">WiFi名称</label>"
    "            <input type=\"text\" id=\"ssid\" name=\"ssid\" class=\"form-control\" "
    "                   placeholder=\"请输入WiFi名称\" required list=\"wifi-list\">"
    "            <datalist id=\"wifi-list\">";

// 扫描到的WiFi列表会动态插入到这里

static const char *ROOT_HTML_2 =
    "            </datalist>"
    "        </div>"
    "        <div class=\"form-group\">"
    "            <label for=\"password\">WiFi密码</label>"
    "            <input type=\"password\" id=\"password\" name=\"password\" "
    "                   class=\"form-control\" placeholder=\"请输入WiFi密码\">"
    "        </div>"
    "        <button type=\"submit\" class=\"btn\">连接到WiFi</button>"
    "    </form>"
    "    <div class=\"status\" id=\"status\"></div>"
    "</div>"
    "<script>"
    "document.querySelector('form').addEventListener('submit', function(e) {"
    "    e.preventDefault();"
    "    "
    "    // 手动构建URL编码的表单数据"
    "    var formData = new URLSearchParams();"
    "    var ssid = document.getElementById('ssid').value;"
    "    var password = document.getElementById('password').value;"
    "    "
    "    if (!ssid || ssid.trim() === '') {"
    "        alert('请输入WiFi名称');"
    "        return;"
    "    }"
    "    "
    "    formData.append('ssid', ssid);"
    "    formData.append('password', password);"
    "    "
    "    fetch('/config', {"
    "        method: 'POST',"
    "        headers: {"
    "            'Content-Type': 'application/x-www-form-urlencoded'"
    "        },"
    "        body: formData.toString()"
    "    })"
    "    .then(response => {"
    "        if (!response.ok) {"
    "            throw new Error('网络响应错误: ' + response.status);"
    "        }"
    "        return response.text();"
    "    })"
    "    .then(data => {"
    "        document.getElementById('status').innerHTML = data;"
    "        document.getElementById('status').className = 'status success';"
    "        setTimeout(() => {"
    "            document.getElementById('status').innerHTML = '配置成功！3秒后设备将重启...';"
    "            setTimeout(() => { location.reload(); }, 3000);"
    "        }, 1000);"
    "    })"
    "    .catch(error => {"
    "        console.error('错误:', error);"
    "        document.getElementById('status').innerHTML = '配置失败: ' + error.message;"
    "        document.getElementById('status').className = 'status error';"
    "    });"
    "});"
    "</script>"
    "</body>"
    "</html>";

static const char *CONTROL_HTML =
    "<!DOCTYPE html>"
    "<html>"
    "<head>"
    "<meta charset='UTF-8'>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=no, viewport-fit=cover'>"
    "<title>单摇杆遥控小车</title>"
    "<style>"
    "    * { margin: 0; padding: 0; box-sizing: border-box; user-select: none; -webkit-tap-highlight-color: transparent; }"
    "    body {"
    "        background: #0a0f1e;"
    "        display: flex;"
    "        justify-content: center;"
    "        align-items: center;"
    "        min-height: 100vh;"
    "        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;"
    "        overflow: hidden;"
    "        position: fixed;"
    "        width: 100%;"
    "        height: 100%;"
    "    }"
    "    .container {"
    "        display: flex;"
    "        flex-direction: column;"
    "        align-items: center;"
    "        justify-content: center;"
    "        width: 100%;"
    "        height: 100%;"
    "        padding: 20px;"
    "    }"
    "    .title {"
    "        font-size: 1.8rem;"
    "        font-weight: bold;"
    "        color: #fff;"
    "        margin-bottom: 20px;"
    "        text-shadow: 0 2px 5px rgba(0,0,0,0.3);"
    "    }"
    "    .joystick-container {"
    "        background: rgba(30, 40, 60, 0.6);"
    "        border-radius: 50%;"
    "        padding: 20px;"
    "        backdrop-filter: blur(5px);"
    "        box-shadow: 0 8px 25px rgba(0,0,0,0.3);"
    "        margin: 20px 0;"
    "    }"
    "    .joystick-zone {"
    "        width: 250px;"
    "        height: 250px;"
    "        background: #1e2a3a;"
    "        border-radius: 50%;"
    "        box-shadow: inset 0 0 10px rgba(0,0,0,0.5), 0 0 0 3px #3a4a6a;"
    "        position: relative;"
    "        touch-action: none;"
    "        cursor: grab;"
    "    }"
    "    .joystick-thumb {"
    "        width: 80px;"
    "        height: 80px;"
    "        background: radial-gradient(circle, #ffaa44, #cc8800);"
    "        border-radius: 50%;"
    "        position: absolute;"
    "        top: 50%; left: 50%;"
    "        transform: translate(-50%, -50%);"
    "        box-shadow: 0 4px 12px rgba(0,0,0,0.4);"
    "        transition: transform 0.05s linear;"
    "        pointer-events: none;"
    "    }"
    "    .value-display {"
    "        margin-top: 30px;"
    "        background: #000000aa;"
    "        padding: 12px 24px;"
    "        border-radius: 40px;"
    "        font-size: 1.2rem;"
    "        color: #0f0;"
    "        font-family: monospace;"
    "        text-align: center;"
    "    }"
    "    .status {"
    "        margin-top: 15px;"
    "        font-size: 0.9rem;"
    "        color: #aaa;"
    "    }"
    "    @media (max-width: 600px) {"
    "        .joystick-zone { width: 200px; height: 200px; }"
    "        .joystick-thumb { width: 65px; height: 65px; }"
    "        .title { font-size: 1.4rem; }"
    "    }"
    "</style>"
    "</head>"
    "<body>"
    "<div class='container'>"
    "    <div class='title'>🎮 单摇杆遥控</div>"
    "    <div class='joystick-container'>"
    "        <div class='joystick-zone' id='joystickZone'>"
    "            <div class='joystick-thumb' id='joystickThumb'></div>"
    "        </div>"
    "    </div>"
    "    <div class='value-display' id='valueDisplay'>Y: 0   X: 0</div>"
    "    <div class='status'>↑↓ 速度 &nbsp;&nbsp; ←→ 转向</div>"
    "</div>"

    "<script>"
    "    (function() {"
    "        const zone = document.getElementById('joystickZone');"
    "        const thumb = document.getElementById('joystickThumb');"
    "        const display = document.getElementById('valueDisplay');"
    "        let active = false;"
    "        let currentX = 0, currentY = 0;"
    "        let maxRadius = 0;"
    "        let centerX = 0, centerY = 0;"
    "        let intervalId = null;"
    "        "
    "        function updateDimensions() {"
    "            const rect = zone.getBoundingClientRect();"
    "            const thumbWidth = thumb.offsetWidth;"
    "            maxRadius = rect.width / 2 - thumbWidth / 2;"
    "            centerX = rect.width / 2;"
    "            centerY = rect.height / 2;"
    "            if (maxRadius < 0) maxRadius = 0;"
    "        }"
    "        "
    "        function updatePosition(clientX, clientY) {"
    "            if (maxRadius <= 0) {"
    "                updateDimensions();"
    "                if (maxRadius <= 0) return;"
    "            }"
    "            const zoneRect = zone.getBoundingClientRect();"
    "            let dx = clientX - (zoneRect.left + centerX);"
    "            let dy = clientY - (zoneRect.top + centerY);"
    "            const distance = Math.hypot(dx, dy);"
    "            if (distance > maxRadius) {"
    "                dx = dx * maxRadius / distance;"
    "                dy = dy * maxRadius / distance;"
    "            }"
    "            currentX = dx / maxRadius;"
    "            currentY = dy / maxRadius;"
    "            thumb.style.transform = `translate(calc(-50% + ${dx}px), calc(-50% + ${dy}px))`;"
    "            display.innerText = `Y: ${Math.round(-currentY * 100)}   X: ${Math.round(currentX * 100)}`;"
    "        }"
    "        "
    "        function resetPosition() {"
    "            currentX = 0; currentY = 0;"
    "            thumb.style.transform = 'translate(-50%, -50%)';"
    "            display.innerText = 'Y: 0   X: 0';"
    "        }"
    "        "
    "        function handleStart(e) {"
    "            e.preventDefault();"
    "            active = true;"
    "            updateDimensions();"
    "            const point = e.touches ? e.touches[0] : e;"
    "            updatePosition(point.clientX, point.clientY);"
    "        }"
    "        function handleMove(e) {"
    "            if (!active) return;"
    "            e.preventDefault();"
    "            const point = e.touches ? e.touches[0] : e;"
    "            updatePosition(point.clientX, point.clientY);"
    "        }"
    "        function handleEnd(e) {"
    "            active = false;"
    "            resetPosition();"
    "        }"
    "        "
    "        zone.addEventListener('touchstart', handleStart, { passive: false });"
    "        zone.addEventListener('touchmove', handleMove, { passive: false });"
    "        zone.addEventListener('touchend', handleEnd);"
    "        zone.addEventListener('touchcancel', handleEnd);"
    "        zone.addEventListener('mousedown', handleStart);"
    "        window.addEventListener('mousemove', handleMove);"
    "        window.addEventListener('mouseup', handleEnd);"
    "        "
    "        window.addEventListener('resize', updateDimensions);"
    "        updateDimensions();"
    "        "
    "        function sendJoystickData() {"
    "            const ly = Math.round(-currentY * 100);"
    "            const rx = Math.round(currentX * 100);"
    "            fetch(`/api/joystick?ly=${ly}&rx=${rx}`)"
    "                .catch(err => console.error('Send error:', err));"
    "        }"
    "        "
    "        intervalId = setInterval(sendJoystickData, 50);"
    "        "
    "        window.addEventListener('beforeunload', function() {"
    "            if (intervalId) clearInterval(intervalId);"
    "        });"
    "    })();"
    "</script>"
    "</body>"
    "</html>";